Internal Server Error: /
Traceback (most recent call last):
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/apple/DjangoProjects/swap_board/swapboard/frontend/views.py", line 9, in index
    return render(request, "frontend/index.html")
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'frontend/bundle.css'
"GET / HTTP/1.1" 500 27
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/apple/DjangoProjects/swap_board/swapboard/frontend/views.py", line 9, in index
    return render(request, "frontend/index.html")
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/apple/.local/share/virtualenvs/swapboard-z72VmFfI/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'frontend/bundle.css'
"GET / HTTP/1.1" 500 27
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\Documents\DjangoProjects\swapboard\frontend\views.py", line 9, in index
    return render(request, "frontend/index.html")
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'frontend/bundle.css'
"GET / HTTP/1.1" 500 27
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\Documents\DjangoProjects\swapboard\frontend\views.py", line 9, in index
    return render(request, "frontend/index.html")
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 153, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\contrib\staticfiles\storage.py", line 420, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'frontend/bundle.css'
"GET / HTTP/1.1" 500 27
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.14, 127.0.0.1:60895]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.16, 127.0.0.1:61791]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.23, 127.0.0.1:62300]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.17, 127.0.0.1:61504]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.14, 127.0.0.1:61504]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.08, 127.0.0.1:62097]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.13, 127.0.0.1:62151]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.08, 127.0.0.1:62184]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.08, 127.0.0.1:62205]
Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\marti\.virtualenvs\swapboard-IYPPdz8a\lib\site-packages\graphql_jwt\decorators.py", line 136, in wrapped_view
    expires = refresh_token.created +\
AttributeError: '__proxy__' object has no attribute 'created'
HTTP POST /graphql 500 [0.08, 127.0.0.1:62205]
